#!/bin/bash
VERSION=0.1.0

# Usage:
#   orcabas outputfile [outputfile...]
#   orcabas -h
#   orcabas -v

function version_page {
  echo "$(basename "$0")" "$VERSION"
}

function help_page {
  version_page
  sed -ne '/#[^!]\(.*\)/{
    /\/#/d
    s/    //
    s/# //p
  }' "$0"
}

TEMP_FOLDER=$(mktemp -d 2>/dev/null || mktemp -d -t 'tmp')

function cleanup {
  rm -rf "$TEMP_FOLDER"
}

trap cleanup EXIT

# Options:
while getopts ":hvn:" opt "$@"; do
  case $opt in
    h)
      # -h show this help message
      help_page
      exit 0
      ;;
    v)
      # -v show version
      version_page
      exit 0
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      exit 1
      ;;
    :)
      echo "Option -$OPTARG requires an argument." >&2
      exit 1
      ;;
  esac
done

shift $((OPTIND-1))

# Examples:

#   $ orcabas *.out
function orca_readbas {
  outputfile=$1
  outputfile_basename=$(basename "$outputfile" ".out")

  sed -n \
      -e '/.*BASIS SET IN INPUT FORMAT.*/,/.*-------------------------------.*/{
        /INFORMATION/d
        p
      }' \
        "$outputfile" | \
          head -n-3 | \
          tail -n+3 \
            > "${outputfile_basename}.gbs"

  to_gaussian "${outputfile_basename}.gbs" \
    > "${outputfile_basename}.gaussian.gbs"
  mv "${outputfile_basename}.gaussian.gbs" "${outputfile_basename}.gbs"
}

function orca_readaux {
  outputfile=$1
  outputfile_basename=$(basename "$outputfile" ".out")

  sed -n \
      -e '/.*AUXILIARY BASIS SET IN INPUT FORMAT.*/,/.*------------------------------------------------------------------------------.*/{
        /Checking for AutoStart/,/now leaving AutoStart/d
        p
      }' \
        "$outputfile" | \
          head -n-1 | \
          tail -n+3 \
            > "${outputfile_basename}-ri.gbs"

  to_gaussian "${outputfile_basename}-ri.gbs" \
    > "${outputfile_basename}-ri.gaussian.gbs"
  mv "${outputfile_basename}-ri.gaussian.gbs" "${outputfile_basename}-ri.gbs"
}

function to_gaussian {
  basisfile=$1

  printf " ****\n"

  sed -e 's/#/!/' \
      -e '/^$/d' \
      -e 's/\(.*\)NewGTO \(.*\)/\1\2     0/' \
      -e 's/\(.*\)NewAuxGTO \(.*\)/\1\2     0/' \
      -e 's/.*end;.*/ ****/' \
        "$basisfile" | \
    awk 'BEGIN{
      n_contr = 0
      new_atom = 1
    }{
      if ($0 == " ****") {
        print $0

        new_atom = 1
      } else if ($1 == "!") {
        print $0
      } else if (new_atom) {
        print $0

        new_atom = 0
      } else if (n_contr > 0) {
        for (i = 2; i <= NF; i++) {
          printf "%20.10f              ", $i
        }
        printf "\n"

        n_contr -= 1
      } else if ($1 == "S" || $1 == "P" || $1 == "D" || $1 == "F" || $1 == "G" || $1 == "H") {
        n_contr = $2
        printf " %-3s %2d %6.2f\n", $1, $2, "1.00"
      } else {
        print $0
      }
    }'

  printf "\n"
}

called_from=$(pwd)

for outputfile in "$@"; do
  if [ -r "$outputfile" ]; then
    cd "$(dirname "$outputfile")"

    orca_readbas "$outputfile"
    orca_readaux "$outputfile"
  else
    echo "  $outputfile does not exist or is not readable."
    exit 1
  fi

  cd "$called_from"
done

# orcabas <https://github.com/chemical-scripts/orcabas>
# is licensed under the MIT License.
